// Generated by CoffeeScript 1.6.3
(function() {
  var basedir, configDir, email;

  basedir = "../../../";

  configDir = basedir + "config/";

  email = require(configDir + "email.js");

  describe("Send mail", function() {
    it('should send mail with information about registration', function(done) {
      email.sendRegisteredMail(555555, "Ismar Slomic", "ismar@slomic.no", 99589889);
      return done();
    });
    return it('should send mail with information about unregistration', function(done) {
      email.sendUnRegisteredMail(555555, "Ismar Slomic", "ismar@slomic.no", 99589889);
      return done();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=emailSpec.map
*/
